// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: event.proto

//go:build !protoopaque

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BettingStatus int32

const (
	BettingStatus_BettingUnknown   BettingStatus = 0
	BettingStatus_BettingOpen      BettingStatus = 1
	BettingStatus_BettingSuspended BettingStatus = 2
	BettingStatus_BettingClosed    BettingStatus = 3
)

// Enum value maps for BettingStatus.
var (
	BettingStatus_name = map[int32]string{
		0: "BettingUnknown",
		1: "BettingOpen",
		2: "BettingSuspended",
		3: "BettingClosed",
	}
	BettingStatus_value = map[string]int32{
		"BettingUnknown":   0,
		"BettingOpen":      1,
		"BettingSuspended": 2,
		"BettingClosed":    3,
	}
)

func (x BettingStatus) Enum() *BettingStatus {
	p := new(BettingStatus)
	*p = x
	return p
}

func (x BettingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BettingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (BettingStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x BettingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type EventVisibility int32

const (
	EventVisibility_VisibilityUnknown   EventVisibility = 0
	EventVisibility_VisibilityDisplayed EventVisibility = 1
	EventVisibility_VisibilityHidden    EventVisibility = 2
)

// Enum value maps for EventVisibility.
var (
	EventVisibility_name = map[int32]string{
		0: "VisibilityUnknown",
		1: "VisibilityDisplayed",
		2: "VisibilityHidden",
	}
	EventVisibility_value = map[string]int32{
		"VisibilityUnknown":   0,
		"VisibilityDisplayed": 1,
		"VisibilityHidden":    2,
	}
)

func (x EventVisibility) Enum() *EventVisibility {
	p := new(EventVisibility)
	*p = x
	return p
}

func (x EventVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventVisibility) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RaceCategory int32

const (
	RaceCategory_RaceCategoryUnknown   RaceCategory = 0
	RaceCategory_RaceCategoryHorse     RaceCategory = 1
	RaceCategory_RaceCategoryGreyhound RaceCategory = 2
	RaceCategory_RaceCategoryHarness   RaceCategory = 3
)

// Enum value maps for RaceCategory.
var (
	RaceCategory_name = map[int32]string{
		0: "RaceCategoryUnknown",
		1: "RaceCategoryHorse",
		2: "RaceCategoryGreyhound",
		3: "RaceCategoryHarness",
	}
	RaceCategory_value = map[string]int32{
		"RaceCategoryUnknown":   0,
		"RaceCategoryHorse":     1,
		"RaceCategoryGreyhound": 2,
		"RaceCategoryHarness":   3,
	}
)

func (x RaceCategory) Enum() *RaceCategory {
	p := new(RaceCategory)
	*p = x
	return p
}

func (x RaceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (RaceCategory) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x RaceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OptionalBettingStatus struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         BettingStatus          `protobuf:"varint,1,opt,name=Value,proto3,enum=model.BettingStatus" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalBettingStatus) Reset() {
	*x = OptionalBettingStatus{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalBettingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalBettingStatus) ProtoMessage() {}

func (x *OptionalBettingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalBettingStatus) GetValue() BettingStatus {
	if x != nil {
		return x.Value
	}
	return BettingStatus_BettingUnknown
}

func (x *OptionalBettingStatus) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalBettingStatus) SetValue(v BettingStatus) {
	x.Value = v
}

func (x *OptionalBettingStatus) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalBettingStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   BettingStatus
	Deleted bool
}

func (b0 OptionalBettingStatus_builder) Build() *OptionalBettingStatus {
	m0 := &OptionalBettingStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalEventVisibility struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         EventVisibility        `protobuf:"varint,1,opt,name=Value,proto3,enum=model.EventVisibility" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalEventVisibility) Reset() {
	*x = OptionalEventVisibility{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalEventVisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalEventVisibility) ProtoMessage() {}

func (x *OptionalEventVisibility) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalEventVisibility) GetValue() EventVisibility {
	if x != nil {
		return x.Value
	}
	return EventVisibility_VisibilityUnknown
}

func (x *OptionalEventVisibility) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalEventVisibility) SetValue(v EventVisibility) {
	x.Value = v
}

func (x *OptionalEventVisibility) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalEventVisibility_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   EventVisibility
	Deleted bool
}

func (b0 OptionalEventVisibility_builder) Build() *OptionalEventVisibility {
	m0 := &OptionalEventVisibility{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalRaceCategory struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         RaceCategory           `protobuf:"varint,1,opt,name=Value,proto3,enum=model.RaceCategory" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRaceCategory) Reset() {
	*x = OptionalRaceCategory{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRaceCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRaceCategory) ProtoMessage() {}

func (x *OptionalRaceCategory) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalRaceCategory) GetValue() RaceCategory {
	if x != nil {
		return x.Value
	}
	return RaceCategory_RaceCategoryUnknown
}

func (x *OptionalRaceCategory) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalRaceCategory) SetValue(v RaceCategory) {
	x.Value = v
}

func (x *OptionalRaceCategory) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalRaceCategory_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   RaceCategory
	Deleted bool
}

func (b0 OptionalRaceCategory_builder) Build() *OptionalRaceCategory {
	m0 := &OptionalRaceCategory{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

// Event models a betting match/race
type Event struct {
	state           protoimpl.MessageState   `protogen:"hybrid.v1"`
	ID              string                   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name            *OptionalString          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime       *OptionalInt64           `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus   *OptionalBettingStatus   `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Markets         []*Market                `protobuf:"bytes,5,rep,name=Markets,proto3" json:"Markets,omitempty"`
	EventTypeID     *OptionalString          `protobuf:"bytes,6,opt,name=EventTypeID,proto3" json:"EventTypeID,omitempty"`
	SportData       *SportEvent              `protobuf:"bytes,7,opt,name=SportData,proto3" json:"SportData,omitempty"`
	EventVisibility *OptionalEventVisibility `protobuf:"bytes,8,opt,name=EventVisibility,proto3" json:"EventVisibility,omitempty"`
	RaceData        *RaceEvent               `protobuf:"bytes,9,opt,name=RaceData,proto3" json:"RaceData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Event) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Event) GetStartTime() *OptionalInt64 {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Event) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *Event) GetEventTypeID() *OptionalString {
	if x != nil {
		return x.EventTypeID
	}
	return nil
}

func (x *Event) GetSportData() *SportEvent {
	if x != nil {
		return x.SportData
	}
	return nil
}

func (x *Event) GetEventVisibility() *OptionalEventVisibility {
	if x != nil {
		return x.EventVisibility
	}
	return nil
}

func (x *Event) GetRaceData() *RaceEvent {
	if x != nil {
		return x.RaceData
	}
	return nil
}

func (x *Event) SetID(v string) {
	x.ID = v
}

func (x *Event) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Event) SetStartTime(v *OptionalInt64) {
	x.StartTime = v
}

func (x *Event) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Event) SetMarkets(v []*Market) {
	x.Markets = v
}

func (x *Event) SetEventTypeID(v *OptionalString) {
	x.EventTypeID = v
}

func (x *Event) SetSportData(v *SportEvent) {
	x.SportData = v
}

func (x *Event) SetEventVisibility(v *OptionalEventVisibility) {
	x.EventVisibility = v
}

func (x *Event) SetRaceData(v *RaceEvent) {
	x.RaceData = v
}

func (x *Event) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Event) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.StartTime != nil
}

func (x *Event) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Event) HasEventTypeID() bool {
	if x == nil {
		return false
	}
	return x.EventTypeID != nil
}

func (x *Event) HasSportData() bool {
	if x == nil {
		return false
	}
	return x.SportData != nil
}

func (x *Event) HasEventVisibility() bool {
	if x == nil {
		return false
	}
	return x.EventVisibility != nil
}

func (x *Event) HasRaceData() bool {
	if x == nil {
		return false
	}
	return x.RaceData != nil
}

func (x *Event) ClearName() {
	x.Name = nil
}

func (x *Event) ClearStartTime() {
	x.StartTime = nil
}

func (x *Event) ClearBettingStatus() {
	x.BettingStatus = nil
}

func (x *Event) ClearEventTypeID() {
	x.EventTypeID = nil
}

func (x *Event) ClearSportData() {
	x.SportData = nil
}

func (x *Event) ClearEventVisibility() {
	x.EventVisibility = nil
}

func (x *Event) ClearRaceData() {
	x.RaceData = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID              string
	Name            *OptionalString
	StartTime       *OptionalInt64
	BettingStatus   *OptionalBettingStatus
	Markets         []*Market
	EventTypeID     *OptionalString
	SportData       *SportEvent
	EventVisibility *OptionalEventVisibility
	RaceData        *RaceEvent
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Markets = b.Markets
	x.EventTypeID = b.EventTypeID
	x.SportData = b.SportData
	x.EventVisibility = b.EventVisibility
	x.RaceData = b.RaceData
	return m0
}

// SportEvent models event details that are specific to sports
type SportEvent struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Name          *OptionalString        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Region        *OptionalString        `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	League        *OptionalString        `protobuf:"bytes,3,opt,name=League,proto3" json:"League,omitempty"`
	Round         *OptionalString        `protobuf:"bytes,4,opt,name=Round,proto3" json:"Round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportEvent) Reset() {
	*x = SportEvent{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportEvent) ProtoMessage() {}

func (x *SportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SportEvent) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SportEvent) GetRegion() *OptionalString {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *SportEvent) GetLeague() *OptionalString {
	if x != nil {
		return x.League
	}
	return nil
}

func (x *SportEvent) GetRound() *OptionalString {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *SportEvent) SetName(v *OptionalString) {
	x.Name = v
}

func (x *SportEvent) SetRegion(v *OptionalString) {
	x.Region = v
}

func (x *SportEvent) SetLeague(v *OptionalString) {
	x.League = v
}

func (x *SportEvent) SetRound(v *OptionalString) {
	x.Round = v
}

func (x *SportEvent) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *SportEvent) HasRegion() bool {
	if x == nil {
		return false
	}
	return x.Region != nil
}

func (x *SportEvent) HasLeague() bool {
	if x == nil {
		return false
	}
	return x.League != nil
}

func (x *SportEvent) HasRound() bool {
	if x == nil {
		return false
	}
	return x.Round != nil
}

func (x *SportEvent) ClearName() {
	x.Name = nil
}

func (x *SportEvent) ClearRegion() {
	x.Region = nil
}

func (x *SportEvent) ClearLeague() {
	x.League = nil
}

func (x *SportEvent) ClearRound() {
	x.Round = nil
}

type SportEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name   *OptionalString
	Region *OptionalString
	League *OptionalString
	Round  *OptionalString
}

func (b0 SportEvent_builder) Build() *SportEvent {
	m0 := &SportEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Region = b.Region
	x.League = b.League
	x.Round = b.Round
	return m0
}

// RaceEvent models event details that are specific to races.
type RaceEvent struct {
	state    protoimpl.MessageState `protogen:"hybrid.v1"`
	Category *OptionalRaceCategory  `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	// Distance is the distance of the race measured in meters.
	Distance      *OptionalInt64  `protobuf:"bytes,2,opt,name=Distance,proto3" json:"Distance,omitempty"`
	RaceCourse    *OptionalString `protobuf:"bytes,3,opt,name=RaceCourse,proto3" json:"RaceCourse,omitempty"`
	State         *OptionalString `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceEvent) Reset() {
	*x = RaceEvent{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceEvent) ProtoMessage() {}

func (x *RaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RaceEvent) GetCategory() *OptionalRaceCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *RaceEvent) GetDistance() *OptionalInt64 {
	if x != nil {
		return x.Distance
	}
	return nil
}

func (x *RaceEvent) GetRaceCourse() *OptionalString {
	if x != nil {
		return x.RaceCourse
	}
	return nil
}

func (x *RaceEvent) GetState() *OptionalString {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RaceEvent) SetCategory(v *OptionalRaceCategory) {
	x.Category = v
}

func (x *RaceEvent) SetDistance(v *OptionalInt64) {
	x.Distance = v
}

func (x *RaceEvent) SetRaceCourse(v *OptionalString) {
	x.RaceCourse = v
}

func (x *RaceEvent) SetState(v *OptionalString) {
	x.State = v
}

func (x *RaceEvent) HasCategory() bool {
	if x == nil {
		return false
	}
	return x.Category != nil
}

func (x *RaceEvent) HasDistance() bool {
	if x == nil {
		return false
	}
	return x.Distance != nil
}

func (x *RaceEvent) HasRaceCourse() bool {
	if x == nil {
		return false
	}
	return x.RaceCourse != nil
}

func (x *RaceEvent) HasState() bool {
	if x == nil {
		return false
	}
	return x.State != nil
}

func (x *RaceEvent) ClearCategory() {
	x.Category = nil
}

func (x *RaceEvent) ClearDistance() {
	x.Distance = nil
}

func (x *RaceEvent) ClearRaceCourse() {
	x.RaceCourse = nil
}

func (x *RaceEvent) ClearState() {
	x.State = nil
}

type RaceEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Category *OptionalRaceCategory
	// Distance is the distance of the race measured in meters.
	Distance   *OptionalInt64
	RaceCourse *OptionalString
	State      *OptionalString
}

func (b0 RaceEvent_builder) Build() *RaceEvent {
	m0 := &RaceEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.Category = b.Category
	x.Distance = b.Distance
	x.RaceCourse = b.RaceCourse
	x.State = b.State
	return m0
}

// Market models a market of betting options e.g Head to Head or Totals
type Market struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime     *OptionalInt64         `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus *OptionalBettingStatus `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Selections    []*Selection           `protobuf:"bytes,5,rep,name=Selections,proto3" json:"Selections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Market) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Market) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Market) GetStartTime() *OptionalInt64 {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Market) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Market) GetSelections() []*Selection {
	if x != nil {
		return x.Selections
	}
	return nil
}

func (x *Market) SetID(v string) {
	x.ID = v
}

func (x *Market) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Market) SetStartTime(v *OptionalInt64) {
	x.StartTime = v
}

func (x *Market) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Market) SetSelections(v []*Selection) {
	x.Selections = v
}

func (x *Market) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Market) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.StartTime != nil
}

func (x *Market) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Market) ClearName() {
	x.Name = nil
}

func (x *Market) ClearStartTime() {
	x.StartTime = nil
}

func (x *Market) ClearBettingStatus() {
	x.BettingStatus = nil
}

type Market_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          *OptionalString
	StartTime     *OptionalInt64
	BettingStatus *OptionalBettingStatus
	Selections    []*Selection
}

func (b0 Market_builder) Build() *Market {
	m0 := &Market{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Selections = b.Selections
	return m0
}

// Selection models a betting options e.g Home Team or Over
type Selection struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BettingStatus *OptionalBettingStatus `protobuf:"bytes,3,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Price         *OptionalDouble        `protobuf:"bytes,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Selection) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Selection) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Selection) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Selection) GetPrice() *OptionalDouble {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Selection) SetID(v string) {
	x.ID = v
}

func (x *Selection) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Selection) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Selection) SetPrice(v *OptionalDouble) {
	x.Price = v
}

func (x *Selection) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Selection) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Selection) HasPrice() bool {
	if x == nil {
		return false
	}
	return x.Price != nil
}

func (x *Selection) ClearName() {
	x.Name = nil
}

func (x *Selection) ClearBettingStatus() {
	x.BettingStatus = nil
}

func (x *Selection) ClearPrice() {
	x.Price = nil
}

type Selection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          *OptionalString
	BettingStatus *OptionalBettingStatus
	Price         *OptionalDouble
}

func (b0 Selection_builder) Build() *Selection {
	m0 := &Selection{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.BettingStatus = b.BettingStatus
	x.Price = b.Price
	return m0
}

type OptionalString struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionalString) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalString) SetValue(v string) {
	x.Value = v
}

func (x *OptionalString) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalString_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   string
	Deleted bool
}

func (b0 OptionalString_builder) Build() *OptionalString {
	m0 := &OptionalString{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalDouble struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalDouble) Reset() {
	*x = OptionalDouble{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalDouble) ProtoMessage() {}

func (x *OptionalDouble) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OptionalDouble) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalDouble) SetValue(v float64) {
	x.Value = v
}

func (x *OptionalDouble) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalDouble_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   float64
	Deleted bool
}

func (b0 OptionalDouble_builder) Build() *OptionalDouble {
	m0 := &OptionalDouble{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalInt64 struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalInt64) Reset() {
	*x = OptionalInt64{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalInt64) ProtoMessage() {}

func (x *OptionalInt64) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalInt64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OptionalInt64) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalInt64) SetValue(v int64) {
	x.Value = v
}

func (x *OptionalInt64) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalInt64_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   int64
	Deleted bool
}

func (b0 OptionalInt64_builder) Build() *OptionalInt64 {
	m0 := &OptionalInt64{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05model\"]\n" +
	"\x15OptionalBettingStatus\x12*\n" +
	"\x05Value\x18\x01 \x01(\x0e2\x14.model.BettingStatusR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"a\n" +
	"\x17OptionalEventVisibility\x12,\n" +
	"\x05Value\x18\x01 \x01(\x0e2\x16.model.EventVisibilityR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"[\n" +
	"\x14OptionalRaceCategory\x12)\n" +
	"\x05Value\x18\x01 \x01(\x0e2\x13.model.RaceCategoryR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"\xc5\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x122\n" +
	"\tStartTime\x18\x03 \x01(\v2\x14.model.OptionalInt64R\tStartTime\x12B\n" +
	"\rBettingStatus\x18\x04 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x12'\n" +
	"\aMarkets\x18\x05 \x03(\v2\r.model.MarketR\aMarkets\x127\n" +
	"\vEventTypeID\x18\x06 \x01(\v2\x15.model.OptionalStringR\vEventTypeID\x12/\n" +
	"\tSportData\x18\a \x01(\v2\x11.model.SportEventR\tSportData\x12H\n" +
	"\x0fEventVisibility\x18\b \x01(\v2\x1e.model.OptionalEventVisibilityR\x0fEventVisibility\x12,\n" +
	"\bRaceData\x18\t \x01(\v2\x10.model.RaceEventR\bRaceData\"\xc2\x01\n" +
	"\n" +
	"SportEvent\x12)\n" +
	"\x04Name\x18\x01 \x01(\v2\x15.model.OptionalStringR\x04Name\x12-\n" +
	"\x06Region\x18\x02 \x01(\v2\x15.model.OptionalStringR\x06Region\x12-\n" +
	"\x06League\x18\x03 \x01(\v2\x15.model.OptionalStringR\x06League\x12+\n" +
	"\x05Round\x18\x04 \x01(\v2\x15.model.OptionalStringR\x05Round\"\xda\x01\n" +
	"\tRaceEvent\x127\n" +
	"\bCategory\x18\x01 \x01(\v2\x1b.model.OptionalRaceCategoryR\bCategory\x120\n" +
	"\bDistance\x18\x02 \x01(\v2\x14.model.OptionalInt64R\bDistance\x125\n" +
	"\n" +
	"RaceCourse\x18\x03 \x01(\v2\x15.model.OptionalStringR\n" +
	"RaceCourse\x12+\n" +
	"\x05State\x18\x04 \x01(\v2\x15.model.OptionalStringR\x05State\"\xed\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x122\n" +
	"\tStartTime\x18\x03 \x01(\v2\x14.model.OptionalInt64R\tStartTime\x12B\n" +
	"\rBettingStatus\x18\x04 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x120\n" +
	"\n" +
	"Selections\x18\x05 \x03(\v2\x10.model.SelectionR\n" +
	"Selections\"\xb7\x01\n" +
	"\tSelection\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x12B\n" +
	"\rBettingStatus\x18\x03 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x12+\n" +
	"\x05Price\x18\x04 \x01(\v2\x15.model.OptionalDoubleR\x05Price\"@\n" +
	"\x0eOptionalString\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"@\n" +
	"\x0eOptionalDouble\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x01R\x05Value\x12\x18\n" +
	"\aDeleted\x18\x03 \x01(\bR\aDeleted\"?\n" +
	"\rOptionalInt64\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x03R\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted*]\n" +
	"\rBettingStatus\x12\x12\n" +
	"\x0eBettingUnknown\x10\x00\x12\x0f\n" +
	"\vBettingOpen\x10\x01\x12\x14\n" +
	"\x10BettingSuspended\x10\x02\x12\x11\n" +
	"\rBettingClosed\x10\x03*W\n" +
	"\x0fEventVisibility\x12\x15\n" +
	"\x11VisibilityUnknown\x10\x00\x12\x17\n" +
	"\x13VisibilityDisplayed\x10\x01\x12\x14\n" +
	"\x10VisibilityHidden\x10\x02*r\n" +
	"\fRaceCategory\x12\x17\n" +
	"\x13RaceCategoryUnknown\x10\x00\x12\x15\n" +
	"\x11RaceCategoryHorse\x10\x01\x12\x19\n" +
	"\x15RaceCategoryGreyhound\x10\x02\x12\x17\n" +
	"\x13RaceCategoryHarness\x10\x03B;Z9git.neds.sh/technology/pricekinetics/tools/codetest/modelb\x06proto3"

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_event_proto_goTypes = []any{
	(BettingStatus)(0),              // 0: model.BettingStatus
	(EventVisibility)(0),            // 1: model.EventVisibility
	(RaceCategory)(0),               // 2: model.RaceCategory
	(*OptionalBettingStatus)(nil),   // 3: model.OptionalBettingStatus
	(*OptionalEventVisibility)(nil), // 4: model.OptionalEventVisibility
	(*OptionalRaceCategory)(nil),    // 5: model.OptionalRaceCategory
	(*Event)(nil),                   // 6: model.Event
	(*SportEvent)(nil),              // 7: model.SportEvent
	(*RaceEvent)(nil),               // 8: model.RaceEvent
	(*Market)(nil),                  // 9: model.Market
	(*Selection)(nil),               // 10: model.Selection
	(*OptionalString)(nil),          // 11: model.OptionalString
	(*OptionalDouble)(nil),          // 12: model.OptionalDouble
	(*OptionalInt64)(nil),           // 13: model.OptionalInt64
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: model.OptionalBettingStatus.Value:type_name -> model.BettingStatus
	1,  // 1: model.OptionalEventVisibility.Value:type_name -> model.EventVisibility
	2,  // 2: model.OptionalRaceCategory.Value:type_name -> model.RaceCategory
	11, // 3: model.Event.Name:type_name -> model.OptionalString
	13, // 4: model.Event.StartTime:type_name -> model.OptionalInt64
	3,  // 5: model.Event.BettingStatus:type_name -> model.OptionalBettingStatus
	9,  // 6: model.Event.Markets:type_name -> model.Market
	11, // 7: model.Event.EventTypeID:type_name -> model.OptionalString
	7,  // 8: model.Event.SportData:type_name -> model.SportEvent
	4,  // 9: model.Event.EventVisibility:type_name -> model.OptionalEventVisibility
	8,  // 10: model.Event.RaceData:type_name -> model.RaceEvent
	11, // 11: model.SportEvent.Name:type_name -> model.OptionalString
	11, // 12: model.SportEvent.Region:type_name -> model.OptionalString
	11, // 13: model.SportEvent.League:type_name -> model.OptionalString
	11, // 14: model.SportEvent.Round:type_name -> model.OptionalString
	5,  // 15: model.RaceEvent.Category:type_name -> model.OptionalRaceCategory
	13, // 16: model.RaceEvent.Distance:type_name -> model.OptionalInt64
	11, // 17: model.RaceEvent.RaceCourse:type_name -> model.OptionalString
	11, // 18: model.RaceEvent.State:type_name -> model.OptionalString
	11, // 19: model.Market.Name:type_name -> model.OptionalString
	13, // 20: model.Market.StartTime:type_name -> model.OptionalInt64
	3,  // 21: model.Market.BettingStatus:type_name -> model.OptionalBettingStatus
	10, // 22: model.Market.Selections:type_name -> model.Selection
	11, // 23: model.Selection.Name:type_name -> model.OptionalString
	3,  // 24: model.Selection.BettingStatus:type_name -> model.OptionalBettingStatus
	12, // 25: model.Selection.Price:type_name -> model.OptionalDouble
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
