version: "2"

run:
  timeout: 5m

issues:
  exclude-files:
    - ".*\\.pb\\.go"

linters:
  enable:
    - errcheck
    - revive
    - staticcheck
    - lll
    - funlen
    - goconst
    - unparam
    - unused
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(git.neds.sh/technology/pricekinetics/tools/codetest)
      custom-order: true
    goimports:
      local-prefixes:
        - git.neds.sh/technology/pricekinetics/tools/codetest
