// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_Update_FullMethodName        = "/core.Service/Update"
	Service_GetSportEvent_FullMethodName = "/core.Service/GetSportEvent"
	Service_GetRaceEvent_FullMethodName  = "/core.Service/GetRaceEvent"
	Service_SearchEvents_FullMethodName  = "/core.Service/SearchEvents"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Update updates an Event and runs the pipeline of transformations
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// GetSportEvent retrieves a model.Event from the database and returns a core.SportEvent
	// this is a more UserConsumable representation of the model that is specific to sport events
	GetSportEvent(ctx context.Context, in *GetSportEventRequest, opts ...grpc.CallOption) (*GetSportEventResponse, error)
	// GetRaceEvent retrieves a model.Event from the database and returns a core.RaceEvent
	// this is a more UserConsumable representation of the model that is specific to race events
	GetRaceEvent(ctx context.Context, in *GetRaceEventRequest, opts ...grpc.CallOption) (*GetRaceEventResponse, error)
	// SearchEvents allows users to search events by date and/or betting status and/or event visibility.
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Service_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetSportEvent(ctx context.Context, in *GetSportEventRequest, opts ...grpc.CallOption) (*GetSportEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSportEventResponse)
	err := c.cc.Invoke(ctx, Service_GetSportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetRaceEvent(ctx context.Context, in *GetRaceEventRequest, opts ...grpc.CallOption) (*GetRaceEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRaceEventResponse)
	err := c.cc.Invoke(ctx, Service_GetRaceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, Service_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// Update updates an Event and runs the pipeline of transformations
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// GetSportEvent retrieves a model.Event from the database and returns a core.SportEvent
	// this is a more UserConsumable representation of the model that is specific to sport events
	GetSportEvent(context.Context, *GetSportEventRequest) (*GetSportEventResponse, error)
	// GetRaceEvent retrieves a model.Event from the database and returns a core.RaceEvent
	// this is a more UserConsumable representation of the model that is specific to race events
	GetRaceEvent(context.Context, *GetRaceEventRequest) (*GetRaceEventResponse, error)
	// SearchEvents allows users to search events by date and/or betting status and/or event visibility.
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
}

// UnimplementedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedServiceServer) GetSportEvent(context.Context, *GetSportEventRequest) (*GetSportEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSportEvent not implemented")
}
func (UnimplementedServiceServer) GetRaceEvent(context.Context, *GetRaceEventRequest) (*GetRaceEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRaceEvent not implemented")
}
func (UnimplementedServiceServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedServiceServer) testEmbeddedByValue() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetSportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSportEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetSportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetSportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetSportEvent(ctx, req.(*GetSportEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetRaceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaceEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetRaceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetRaceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetRaceEvent(ctx, req.(*GetRaceEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Service_Update_Handler,
		},
		{
			MethodName: "GetSportEvent",
			Handler:    _Service_GetSportEvent_Handler,
		},
		{
			MethodName: "GetRaceEvent",
			Handler:    _Service_GetRaceEvent_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _Service_SearchEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
